import { defineToolcraft } from "@/toolcraft/runtime";

import { pointerSection, pinsSection } from "@/dither/interaction-controls";

import { appIdentity } from "./app-identity";

const always = { mode: "always" } as const;
const whenEnabled = (target: string) => ({
  all: [{ equals: true, target }],
  mode: "conditional",
} as const);

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: true,
  },
  identity: appIdentity,
  panels: {
    controls: {
      sections: [
        {
          controls: {
            includeBackground: {
              applicability: always,
              defaultValue: true,
              label: "Include",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              applicability: always,
              defaultValue: "#0A0A0A",
              label: false,
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          id: "background",
          title: "Background",
        },
        {
          controls: {
            image: {
              accept: "image/jpeg,image/png",
              applicability: always,
              assetKind: "image",
              defaultValue: null,
              label: "Image",
              performanceReason:
                "Import changes the source-bound cache while runtime media owns bytes and transforms.",
              performanceRole: "responsiveness",
              target: "source.image",
              type: "fileDrop",
            },
          },
          id: "source",
          title: "Source",
        },
        {
          controls: {
            blur: {
              applicability: always,
              defaultValue: 0,
              label: "Blur",
              max: 24,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.25,
              target: "tone.blur",
              type: "slider",
              unit: "px",
            },
            grain: {
              applicability: always,
              defaultValue: 0.07,
              label: "Grain",
              max: 0.5,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: "tone.grain",
              type: "slider",
            },
            gamma: {
              applicability: always,
              defaultValue: 2,
              label: "Gamma",
              max: 4,
              min: 0.25,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "tone.gamma",
              type: "slider",
            },
            blackPoint: {
              applicability: always,
              defaultValue: 0,
              label: "Black point",
              max: 254,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "tone.blackPoint",
              type: "slider",
            },
            whitePoint: {
              applicability: always,
              defaultValue: 251,
              label: "White point",
              max: 255,
              min: 1,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "tone.whitePoint",
              type: "slider",
            },
          },
          id: "tone",
          title: "Tone",
        },
        {
          controls: {
            algorithm: {
              applicability: always,
              defaultValue: "floyd-steinberg",
              label: "Algorithm",
              options: [
                { label: "F-S", value: "floyd-steinberg" },
                { label: "Bayer", value: "bayer" },
                { label: "Random", value: "random" },
              ],
              performanceRole: "responsiveness",
              target: "dither.algorithm",
              type: "segmented",
            },
            pixelSize: {
              applicability: always,
              defaultValue: 2,
              description: "Smaller cells generate more dither samples.",
              label: "Pixel size",
              max: 16,
              min: 1,
              performanceReason:
                "The minimum cell size produces the maximum dither sample density.",
              performanceRole: "workload",
              sliderValueKind: "continuous",
              step: 1,
              target: "dither.pixelSize",
              type: "slider",
              unit: "px",
            },
            threshold: {
              applicability: always,
              defaultValue: 128,
              label: "Threshold",
              max: 255,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "dither.threshold",
              type: "slider",
            },
            invert: {
              applicability: always,
              defaultValue: false,
              label: "Invert",
              performanceRole: "responsiveness",
              target: "dither.invert",
              type: "switch",
            },
            ink: {
              applicability: always,
              defaultValue: "#F4F1EA",
              label: "Particle color",
              description: "Base color of the particles; pins keep their independent accent colors.",
              performanceRole: "responsiveness",
              target: "dither.ink",
              type: "color",
            },
          },
          id: "dither",
          title: "Dither",
        },
        {
          controls: {
            flickerEnabled: {
              applicability: always,
              defaultValue: true,
              label: "Flicker",
              performanceRole: "responsiveness",
              target: "motion.flicker.enabled",
              type: "switch",
            },
            flickerAmount: {
              applicability: whenEnabled("motion.flicker.enabled"),
              defaultValue: 0.65,
              label: "Variation",
              description: "How deeply independent particles fade: zero preserves the image, one allows complete disappearance.",
              max: 1,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: "motion.flicker.amount",
              type: "slider",
            },
            flickerSpeed: {
              applicability: whenEnabled("motion.flicker.enabled"),
              defaultValue: 1,
              description: "Rate of independent fade events within the timeline loop; the loop remains seamless.",
              label: "Speed",
              max: 4,
              min: 0.25,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "motion.flicker.speed",
              type: "slider",
            },
            breathingEnabled: {
              applicability: always,
              defaultValue: true,
              label: "Breathing",
              performanceRole: "responsiveness",
              target: "motion.breathing.enabled",
              type: "switch",
            },
            breathingAmount: {
              applicability: whenEnabled("motion.breathing.enabled"),
              defaultValue: 0.08,
              label: "Amount",
              max: 0.35,
              min: 0,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: "motion.breathing.amount",
              type: "slider",
            },
          },
          id: "motion",
          title: "Motion",
        },
        pointerSection,
        pinsSection,
        {
          controls: {
            imageFormat: {
              applicability: always,
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              applicability: always,
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason:
                "The runtime export frame dimension captures resolution workload directly.",
              performanceRole: "responsiveness",
              target: "export.image.resolution",
              type: "select",
            },
          },
          id: "image-export",
          layoutGroups: [{ columns: 2, controls: ["imageFormat", "imageResolution"], layout: "inline" }],
          title: "Image Export",
        },
        {
          controls: {
            videoFormat: {
              applicability: always,
              defaultValue: "mp4",
              label: "Format",
              options: [
                { label: "MP4", value: "mp4" },
                { label: "WebM", value: "webm" },
              ],
              performanceRole: "responsiveness",
              target: "export.video.format",
              type: "select",
            },
            videoResolution: {
              applicability: always,
              defaultValue: "current",
              label: "Resolution",
              options: [
                { label: "Current", value: "current" },
                { label: "4K", value: "4k" },
              ],
              performanceReason:
                "The runtime export frame dimension captures resolution workload directly.",
              performanceRole: "responsiveness",
              target: "export.video.resolution",
              type: "select",
            },
          },
          id: "video-export",
          layoutGroups: [{ columns: 2, controls: ["videoFormat", "videoResolution"], layout: "inline" }],
          title: "Video Export",
        },
        {
          actionGroup: "secondary",
          controls: {
            outputActions: {
              applicability: always,
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  role: "export-image",
                  value: "export.png",
                },
                {
                  icon: "upload-simple",
                  label: "Export Video",
                  role: "export-video",
                  value: "export.video",
                },
              ],
              target: "actions.output",
              type: "panelActions",
            },
          },
          id: "export-actions",
          title: "Export",
        },
      ],
      title: "Dither controls",
    },
    timeline: {
      defaultDurationSeconds: 7.2,
      enabled: true,
      mode: "playback",
    },
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
